name: Code Style

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/lint.yml"
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/lint.yml"
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"

jobs:
  test:
    name: Tests on ${{ matrix.os }} for ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: cargo build
        run: cargo build

      - name: cargo fmt
        run: cargo fmt

      - name: cargo clippy
        run: cargo clippy --tests -- -D warnings

      - name: cargo clippy without default features
        run: cargo clippy --no-default-features --tests -- -D warnings
